-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-09-12 17:52:57 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- student id: 34194037(Sachin Shivaramaiah); 33922721(Duolisen); 33751226(Jinxu Tao)
-- Group name:A02_Group032
-- Member name:Sachin Shivaramaiah; Duolisen; Jinxu Tao
-- Capture run of script in file called pf_schema_output.txt

set echo on
SPOOL pf_schema_output.txt


DROP TABLE clinic CASCADE CONSTRAINTS;

DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE participant CASCADE CONSTRAINTS;

DROP TABLE pet CASCADE CONSTRAINTS;

DROP TABLE pet_type CASCADE CONSTRAINTS;

DROP TABLE prescribe CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE service_acc CASCADE CONSTRAINTS;

DROP TABLE specialisation CASCADE CONSTRAINTS;

DROP TABLE training CASCADE CONSTRAINTS;

DROP TABLE vet CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE clinic (
    clinic_id      NUMBER(7) NOT NULL,
    clinic_name    VARCHAR2(25) NOT NULL,
    clinic_address VARCHAR2(50) NOT NULL,
    clinic_pho_num CHAR(10) NOT NULL,
    vet_id         NUMBER(7) NOT NULL
);

COMMENT ON COLUMN clinic.clinic_id IS
    'identification number of clinic';

COMMENT ON COLUMN clinic.clinic_name IS
    'name of clinic';

COMMENT ON COLUMN clinic.clinic_address IS
    'address of clinic';

COMMENT ON COLUMN clinic.clinic_pho_num IS
    'phone number of clinic';

COMMENT ON COLUMN clinic.vet_id IS
    'identification number of vet';

CREATE UNIQUE INDEX clinic__idx ON
    clinic (
        vet_id
    ASC );

ALTER TABLE clinic ADD CONSTRAINT clinic_pk PRIMARY KEY ( clinic_id );

CREATE TABLE drug (
    drug_id             NUMBER(7) NOT NULL,
    drug_name           VARCHAR2(25) NOT NULL,
    drug_usage          VARCHAR2(50) NOT NULL,
    drug_standard_price NUMBER(5, 2) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'Identification number for Drug';

COMMENT ON COLUMN drug.drug_name IS
    'Name of the Drug';

COMMENT ON COLUMN drug.drug_usage IS
    'Usage instruction of the drug';

COMMENT ON COLUMN drug.drug_standard_price IS
    'Fee charged for total qty of drugs. ';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE owner (
    owner_id       NUMBER(7) NOT NULL,
    owner_givname  VARCHAR2(25),
    owner_famname  VARCHAR2(25),
    owner_cont_num CHAR(10) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'identification number for owner';

COMMENT ON COLUMN owner.owner_givname IS
    'owner''s given name';

COMMENT ON COLUMN owner.owner_famname IS
    'owner''s family name';

COMMENT ON COLUMN owner.owner_cont_num IS
    'owner''s contact number';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE participant (
    partici_vet_id       NUMBER(7) NOT NULL,
    train_id             NUMBER(7) NOT NULL,
    partici_train_complt VARCHAR2(1) NOT NULL,
    partici_train_expiry DATE
);

ALTER TABLE participant
    ADD CONSTRAINT chk_training_completion CHECK ( partici_train_complt IN ( 'N', 'Y'
    ) );

COMMENT ON COLUMN participant.partici_vet_id IS
    'the id of vet who accepts training ';

COMMENT ON COLUMN participant.train_id IS
    'identifier for traning ';

COMMENT ON COLUMN participant.partici_train_complt IS
    'completion of training (Y for completed, N for incompleted)';

COMMENT ON COLUMN participant.partici_train_expiry IS
    'expiry date for training';

ALTER TABLE participant ADD CONSTRAINT panticipant_pk PRIMARY KEY ( train_id,
                                                                    partici_vet_id );

CREATE TABLE pet (
    pet_id          NUMBER(7) NOT NULL,
    pet_name        VARCHAR2(15),
    pet_year_born   CHAR(4) NOT NULL,
    pet_life_status CHAR(1) NOT NULL,
    pet_type_id     NUMBER(7) NOT NULL,
    owner_id        NUMBER(7) NOT NULL
);

ALTER TABLE pet
    ADD CONSTRAINT chk_animal_life_status CHECK ( pet_life_status IN ( 'A', 'D' ) );

COMMENT ON COLUMN pet.pet_id IS
    'identifier of pet';

COMMENT ON COLUMN pet.pet_name IS
    'animal''s name';

COMMENT ON COLUMN pet.pet_year_born IS
    'the year animal borned';

COMMENT ON COLUMN pet.pet_life_status IS
    'Idetifier to check if the animal is Alive or Dead (A/D)';

COMMENT ON COLUMN pet.pet_type_id IS
    'identification of animal type';

COMMENT ON COLUMN pet.owner_id IS
    'identification number for owner';

ALTER TABLE pet ADD CONSTRAINT pet_pk PRIMARY KEY ( pet_id );

CREATE TABLE pet_type (
    pet_type_id NUMBER(7) NOT NULL,
    pet_type    VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN pet_type.pet_type_id IS
    'identification of animal type';

COMMENT ON COLUMN pet_type.pet_type IS
    'animal type';

ALTER TABLE pet_type ADD CONSTRAINT animal_type_pk PRIMARY KEY ( pet_type_id );

CREATE TABLE prescribe (
    pres_no               NUMBER(7) NOT NULL,
    visit_date_time       DATE NOT NULL,
    vet_id                NUMBER(7) NOT NULL,
    drug_id               NUMBER(7) NOT NULL,
    pres_drug_dose        VARCHAR2(10) NOT NULL,
    pres_drug_frequency   VARCHAR2(15) NOT NULL,
    pres_drug_qtysupplied NUMBER(3) NOT NULL,
    pres_drug_linecost    NUMBER(5, 3) NOT NULL
);

COMMENT ON COLUMN prescribe.pres_no IS
    'Identifier for prescription with respect to surrogate key.';

COMMENT ON COLUMN prescribe.visit_date_time IS
    'date and time of the visit';

COMMENT ON COLUMN prescribe.vet_id IS
    'identification number of vet';

COMMENT ON COLUMN prescribe.drug_id IS
    'Identification number for Drug';

COMMENT ON COLUMN prescribe.pres_drug_dose IS
    'the dose of drug';

COMMENT ON COLUMN prescribe.pres_drug_frequency IS
    'the frequency of drug';

COMMENT ON COLUMN prescribe.pres_drug_qtysupplied IS
    'the quantity supplied of drug';

COMMENT ON COLUMN prescribe.pres_drug_linecost IS
    'the line cost of drug';

ALTER TABLE prescribe ADD CONSTRAINT prescribe_pk PRIMARY KEY ( pres_no );

ALTER TABLE prescribe
    ADD CONSTRAINT prescribe_nk UNIQUE ( visit_date_time,
                                         vet_id,
                                         drug_id );

CREATE TABLE service (
    service_code           NUMBER(7) NOT NULL,
    service_desc           VARCHAR2(80) NOT NULL,
    service_standard_price NUMBER(5, 2) NOT NULL
);

COMMENT ON COLUMN service.service_code IS
    'identifier for service';

COMMENT ON COLUMN service.service_desc IS
    'the description of service';

COMMENT ON COLUMN service.service_standard_price IS
    'Fee charged for provided service.';

ALTER TABLE service ADD CONSTRAINT service_pk PRIMARY KEY ( service_code );

CREATE TABLE service_acc (
    service_acc_id       NUMBER(7) NOT NULL,
    visit_date_time      DATE NOT NULL,
    vet_id               NUMBER(7) NOT NULL,
    service_code         NUMBER(7) NOT NULL,
    service_acc_linecost NUMBER(5, 2) NOT NULL
);

COMMENT ON COLUMN service_acc.service_acc_id IS
    'the surrogate key for service_acc';

COMMENT ON COLUMN service_acc.visit_date_time IS
    'date and time of the visit';

COMMENT ON COLUMN service_acc.vet_id IS
    'identification number of vet';

COMMENT ON COLUMN service_acc.service_code IS
    'identifier for service';

COMMENT ON COLUMN service_acc.service_acc_linecost IS
    'the line cost for service';

ALTER TABLE service_acc ADD CONSTRAINT service_acc_pk PRIMARY KEY ( service_acc_id );

ALTER TABLE service_acc
    ADD CONSTRAINT service_acc_nk UNIQUE ( visit_date_time,
                                           service_code,
                                           vet_id );

CREATE TABLE specialisation (
    spec_id   NUMBER(7) NOT NULL,
    spec_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN specialisation.spec_id IS
    'identifier for vet specialisation ID ';

COMMENT ON COLUMN specialisation.spec_name IS
    'Newly discovered  specialisation of the vet';

ALTER TABLE specialisation ADD CONSTRAINT vet_specialisation_pk PRIMARY KEY ( spec_id
);

CREATE TABLE training (
    train_id        NUMBER(7) NOT NULL,
    train_date_time DATE NOT NULL,
    vet_id          NUMBER(7) NOT NULL,
    train_name      VARCHAR2(25) NOT NULL,
    train_duration  VARCHAR2(10) NOT NULL,
    clinic_id       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN training.train_id IS
    'identifier for traning ';

COMMENT ON COLUMN training.train_date_time IS
    'Date and time of traning. ';

COMMENT ON COLUMN training.vet_id IS
    'identification number of vet';

COMMENT ON COLUMN training.train_name IS
    'Name of the trainig conducted';

COMMENT ON COLUMN training.train_duration IS
    'Duration of the training conducted';

COMMENT ON COLUMN training.clinic_id IS
    'identification number of clinic';

ALTER TABLE training ADD CONSTRAINT training_pk PRIMARY KEY ( train_id );

ALTER TABLE training ADD CONSTRAINT training_fk UNIQUE ( vet_id,
                                                         train_date_time );

CREATE TABLE vet (
    vet_id            NUMBER(7) NOT NULL,
    vet_givname       VARCHAR2(25),
    vet_famname       VARCHAR2(25),
    vet_cont_num      CHAR(10) NOT NULL,
    vet_employed_date DATE NOT NULL,
    clinic_id         NUMBER(7) NOT NULL,
    spec_id           NUMBER(7)
);

COMMENT ON COLUMN vet.vet_id IS
    'identification number of vet';

COMMENT ON COLUMN vet.vet_givname IS
    'vet''s given name';

COMMENT ON COLUMN vet.vet_famname IS
    'vet''s family name';

COMMENT ON COLUMN vet.vet_cont_num IS
    'contact number of vet';

COMMENT ON COLUMN vet.vet_employed_date IS
    'employed date of vet';

COMMENT ON COLUMN vet.clinic_id IS
    'identification number of clinic';

COMMENT ON COLUMN vet.spec_id IS
    'identifier for vet specialisation ID ';

ALTER TABLE vet ADD CONSTRAINT vet_pk PRIMARY KEY ( vet_id );

CREATE TABLE visit (
    visit_date_time     DATE NOT NULL,
    vet_id              NUMBER(7) NOT NULL,
    visit_length        VARCHAR2(25) NOT NULL,
    visit_pet_note      VARCHAR2(100),
    visit_pet_weight    NUMBER(3, 1) NOT NULL,
    visit_total_cost    NUMBER(5, 2) NOT NULL,
    visit_paidby        CHAR(4) NOT NULL,
    pet_id              NUMBER(7) NOT NULL,
    clinic_id           NUMBER(7) NOT NULL,
    follow_up_date_time DATE,
    follow_up_vet_id    NUMBER(7)
);

ALTER TABLE visit
    ADD CONSTRAINT chk_visit_paidby CHECK ( visit_paidby IN ( 'CASH', 'EFT' ) );

COMMENT ON COLUMN visit.visit_date_time IS
    'date and time of the visit';

COMMENT ON COLUMN visit.vet_id IS
    'identification number of vet';

COMMENT ON COLUMN visit.visit_length IS
    'length of the visit';

COMMENT ON COLUMN visit.visit_pet_note IS
    'the note for one pet in a visit';

COMMENT ON COLUMN visit.visit_pet_weight IS
    'weight of the pet in the visit';

COMMENT ON COLUMN visit.visit_total_cost IS
    'total cost of visit';

COMMENT ON COLUMN visit.visit_paidby IS
    'paymethod of the visit';

COMMENT ON COLUMN visit.pet_id IS
    'identifier of pet';

COMMENT ON COLUMN visit.clinic_id IS
    'identification number of clinic';

COMMENT ON COLUMN visit.follow_up_date_time IS
    'date and time of the visit';

COMMENT ON COLUMN visit.follow_up_vet_id IS
    'identification number of vet';

ALTER TABLE visit ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_date_time,
                                                        vet_id );

ALTER TABLE pet
    ADD CONSTRAINT animaltype_pet FOREIGN KEY ( pet_type_id )
        REFERENCES pet_type ( pet_type_id );

ALTER TABLE vet
    ADD CONSTRAINT clinic_belng_vet FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE training
    ADD CONSTRAINT clinic_training FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE visit
    ADD CONSTRAINT clinic_visit FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE prescribe
    ADD CONSTRAINT drug_prescribe FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE clinic
    ADD CONSTRAINT headvet_clinic FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE pet
    ADD CONSTRAINT owner_pet FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE visit
    ADD CONSTRAINT pet_visit FOREIGN KEY ( pet_id )
        REFERENCES pet ( pet_id );

ALTER TABLE service_acc
    ADD CONSTRAINT service_service_acc FOREIGN KEY ( service_code )
        REFERENCES service ( service_code );

ALTER TABLE participant
    ADD CONSTRAINT training_panticipant FOREIGN KEY ( train_id )
        REFERENCES training ( train_id );

ALTER TABLE vet
    ADD CONSTRAINT vet_specialisation FOREIGN KEY ( spec_id )
        REFERENCES specialisation ( spec_id );

ALTER TABLE training
    ADD CONSTRAINT vet_training FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE visit
    ADD CONSTRAINT vet_visit FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE visit
    ADD CONSTRAINT visit_followup FOREIGN KEY ( follow_up_date_time,
                                                follow_up_vet_id )
        REFERENCES visit ( visit_date_time,
                           vet_id );

ALTER TABLE prescribe
    ADD CONSTRAINT visit_prescribe FOREIGN KEY ( visit_date_time,
                                                 vet_id )
        REFERENCES visit ( visit_date_time,
                           vet_id );

ALTER TABLE service_acc
    ADD CONSTRAINT visit_service_acc FOREIGN KEY ( visit_date_time,
                                                   vet_id )
        REFERENCES visit ( visit_date_time,
                           vet_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             1
-- ALTER TABLE                             35
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off